const screens={
  today:{title:'今日の画面',text:'予約・タスク・業務連絡・顧客の変化を一覧表示',html:'<div class="demo-top"><b>今日の状況</b><span>おはようございます。店舗の状況を確認しましょう</span></div><div class="dashboard-overview"><article class="dashboard-card booking-card"><div class="dashboard-card-head"><i class="dashboard-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16M8 14h3M8 17h6"/></svg></i><p>今日の予約</p></div><strong class="dashboard-count">3<span>件</span></strong><ul class="dashboard-list"><li><b>10:00</b> スタッフAと打ち合わせ</li><li><b>14:00</b> グループレッスン</li><li><b>17:30</b> 業者A様と打ち合わせ</li></ul><span class="dashboard-link">すべての予約を確認 →</span></article><article class="dashboard-card task-card"><div class="dashboard-card-head"><i class="dashboard-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2M15 4V2M8 11l2 2 4-4M8 17h8"/></svg></i><p>今日やること</p></div><strong class="dashboard-count">4<span>件</span></strong><ul class="dashboard-list task-list"><li>✓ 朝の予約確認</li><li>✓ 新規体験が1件あります。<br>情報を確認してください</li><li>○ 月1回の燃えるゴミの日</li><li>○ 業者B様へ返信確認</li></ul><span class="dashboard-link">すべてのタスクを見る →</span></article><article class="dashboard-card notice-card"><div class="dashboard-card-head"><i class="dashboard-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 12h4l7-5v10l-7-5H4zM8 17l1.5 3M18 9.5c1 .7 1.5 1.5 1.5 2.5s-.5 1.8-1.5 2.5"/></svg></i><p>業務連絡</p></div><div class="notice-copy">来月のシフトを<br>提出日です</div><span class="unread-chip">未確認 2名</span><span class="dashboard-link">すべての連絡を見る →</span></article><article class="dashboard-card customer-card"><div class="dashboard-card-head"><i class="dashboard-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="10" cy="8" r="3"/><path d="M4 20c.7-4 2.8-6 6-6s5.3 2 6 6M17 5.5v4M15 7.5h4"/></svg></i><p>顧客の変化</p></div><div class="customer-insight"><small>新規</small><strong>新規体験が1件あります</strong><p>情報を確認してください</p></div><span class="dashboard-link">すべての顧客情報を見る →</span></article></div>'},
  calendar:{title:'予約・カレンダー',text:'グループ予約・マンツーマン予約に対応。定員やキャンセル締切も店舗ごとに設定できます。',html:'<div class="demo-calendar"><div class="calendar-head"><b>2026年9月</b><span>‹　今週　›</span></div><div class="week"><b>月 7</b><b>火 8</b><b class="now">水 9</b><b>木 10</b><b>金 11</b><b>土 12</b><b>日 13</b></div><div class="calendar-body"><i>10:00</i><strong class="booking a">パーソナル予約</strong><i>11:30</i><strong class="booking b">体験カウンセリング</strong><i>14:00</i><strong class="booking c">グループレッスン　残り2席</strong></div></div>'},
  customers:{title:'顧客管理',text:'顧客情報・来店履歴・新規・体験・最近来ていないお客様まで確認。',html:'<div class="demo-list"><div class="list-head">顧客名 <span>最終来店　　状態</span></div><div>佐藤 美咲 <span>9月8日　 <b>継続中</b></span></div><div>田中 健太 <span>9月4日　 <b>体験</b></span></div><div>山本 由美 <span>8月20日　 <em>フォロー対象</em></span></div><div>鈴木 大輔 <span>8月14日　 <em>フォロー対象</em></span></div></div>'},
  sales:{title:'売上・分析',text:'実売上・来店数・月末着地予測などを可視化。',html:'<div class="demo-sales"><article><p>今月の売上</p><b>¥486,200</b><small>↗ 先月比 8.2%</small></article><article><p>月末着地予測</p><b>¥720,000</b><small>目標まで ¥80,000</small></article><div class="chart-demo"></div></div>'},
  staff:{title:'スタッフ共有・タスク',text:'定例業務・共有事項・期限・確認状況まで管理。誰が確認したかも分かります。',html:'<div class="demo-list"><div class="list-head">共有事項 <span>期限　　　確認</span></div><div>明日のシフト確認 <span>9/10　 <b>4/6名</b></span></div><div>月次の清掃チェック <span>9/12　 <b>6/6名</b></span></div><div>新規メニューの案内 <span>9/15　 <em>2/6名</em></span></div></div>'}
};
const panel=document.querySelector('#screen-panel');
function renderScreen(key){const s=screens[key];panel.innerHTML=`<div class="screen-copy"><h3>${s.title}</h3><p>${s.text}</p></div><div class="product-demo">${s.html}</div>`}
document.querySelectorAll('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-screen]').forEach(item=>item.classList.toggle('active',item===btn));renderScreen(btn.dataset.screen)}));
renderScreen('today');
